//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Keyboard_Mapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aliases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aliases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Personal_Keyboard_Mapper.Properties.aliases", typeof(aliases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lewy klawisz myszy.
        /// </summary>
        internal static string leftMouseClick {
            get {
                return ResourceManager.GetString("leftMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podwójny lewy klawisz myszy.
        /// </summary>
        internal static string leftMouseDoubleClick {
            get {
                return ResourceManager.GetString("leftMouseDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przytrzymanie lewego klawisza myszy.
        /// </summary>
        internal static string leftMouseHoldClick {
            get {
                return ResourceManager.GetString("leftMouseHoldClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prawy klawisz myszy.
        /// </summary>
        internal static string rightMouseClick {
            get {
                return ResourceManager.GetString("rightMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podwójny prawy klawisz myszy.
        /// </summary>
        internal static string rightMouseDoubleClick {
            get {
                return ResourceManager.GetString("rightMouseDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przytrzymanie prawego klawisza myszy.
        /// </summary>
        internal static string rightMouseHoldClick {
            get {
                return ResourceManager.GetString("rightMouseHoldClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spacja.
        /// </summary>
        internal static string spacebar {
            get {
                return ResourceManager.GetString("spacebar", resourceCulture);
            }
        }
    }
}
