//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Personal_Keyboard_Mapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę najpierw wybrać akcję.
        /// </summary>
        internal static string ActionNotChoosenMsg {
            get {
                return ResourceManager.GetString("ActionNotChoosenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream alt {
            get {
                return ResourceManager.GetStream("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne konfiguracje.
        /// </summary>
        internal static string avaliableConfigLabel_Text {
            get {
                return ResourceManager.GetString("avaliableConfigLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Column0_HeaderText {
            get {
                return ResourceManager.GetString("Column0.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Column1_HeaderText {
            get {
                return ResourceManager.GetString("Column1.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Column2_HeaderText {
            get {
                return ResourceManager.GetString("Column2.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Column3_HeaderText {
            get {
                return ResourceManager.GetString("Column3.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Column4_HeaderText {
            get {
                return ResourceManager.GetString("Column4.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Column5_HeaderText {
            get {
                return ResourceManager.GetString("Column5.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Column6_HeaderText {
            get {
                return ResourceManager.GetString("Column6.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Column7_HeaderText {
            get {
                return ResourceManager.GetString("Column7.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Column8_HeaderText {
            get {
                return ResourceManager.GetString("Column8.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Column9_HeaderText {
            get {
                return ResourceManager.GetString("Column9.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrana akcja już istnieje, proszę wybrać inną.
        /// </summary>
        internal static string CombinationExistsMsg {
            get {
                return ResourceManager.GetString("CombinationExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kombinacji.
        /// </summary>
        internal static string CombinationList {
            get {
                return ResourceManager.GetString("CombinationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualna konfiguracja.
        /// </summary>
        internal static string CombinationsPanel_Text {
            get {
                return ResourceManager.GetString("CombinationsPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja.
        /// </summary>
        internal static string ConfigGroupBox_Text {
            get {
                return ResourceManager.GetString("ConfigGroupBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nazwę konfiguracji.
        /// </summary>
        internal static string ConfigNameEmpty {
            get {
                return ResourceManager.GetString("ConfigNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa konfiguracji.
        /// </summary>
        internal static string ConfigNameLabel_Text {
            get {
                return ResourceManager.GetString("ConfigNameLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ctrl {
            get {
                return ResourceManager.GetStream("ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja konfiguracji.
        /// </summary>
        internal static string EditConfigBtn_Text {
            get {
                return ResourceManager.GetString("EditConfigBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak konfiguracji, proszę stworzyć nową.
        /// </summary>
        internal static string EmptyConfiguratinMsg {
            get {
                return ResourceManager.GetString("EmptyConfiguratinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokazuj okno pomocy dla kombinacji.
        /// </summary>
        internal static string HelpWindowOn {
            get {
                return ResourceManager.GetString("HelpWindowOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okno pomocy.
        /// </summary>
        internal static string HelpWndChckBox_Text {
            get {
                return ResourceManager.GetString("HelpWndChckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream key1 {
            get {
                return ResourceManager.GetStream("key1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream key2 {
            get {
                return ResourceManager.GetStream("key2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcja naciśnięcia klawisza.
        /// </summary>
        internal static string KeyActionRadioBtn_Text {
            get {
                return ResourceManager.GetString("KeyActionRadioBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcja naciśnięcia klawisza myszy.
        /// </summary>
        internal static string MouseActionRadioBtn_Text {
            get {
                return ResourceManager.GetString("MouseActionRadioBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa konfiguracja.
        /// </summary>
        internal static string NewConfigBtn_Text {
            get {
                return ResourceManager.GetString("NewConfigBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje.
        /// </summary>
        internal static string OptionsGroup_Text {
            get {
                return ResourceManager.GetString("OptionsGroup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz akcję.
        /// </summary>
        internal static string saveActionBtn_Text {
            get {
                return ResourceManager.GetString("saveActionBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz konfigurację.
        /// </summary>
        internal static string SaveConfigBtn_Text {
            get {
                return ResourceManager.GetString("SaveConfigBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream shift {
            get {
                return ResourceManager.GetStream("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz drzwięk klawiszy.
        /// </summary>
        internal static string SoundChckBox_Text {
            get {
                return ResourceManager.GetString("SoundChckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wznów działanie.
        /// </summary>
        internal static string startAppBtn_Text {
            get {
                return ResourceManager.GetString("startAppBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj działanie  .
        /// </summary>
        internal static string stopAppBtn_Text {
            get {
                return ResourceManager.GetString("stopAppBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcja wprowadzania tekstu.
        /// </summary>
        internal static string TextActionRadioBtn_Text {
            get {
                return ResourceManager.GetString("TextActionRadioBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream win {
            get {
                return ResourceManager.GetStream("win", resourceCulture);
            }
        }
    }
}
